[package]
name = "graph-view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.12"
bevy-inspector-egui="0.21"
bevy_window="0.12"
bevy_egui="0.23"
rand="*"
bevy_panorbit_camera = "0.9"
